### ISSUE TITLE
OperationalError: could not translate host name "db" to address: Name or service not known

### ISSUE THREAD

**Issue by nrdout** [ERP-Ukraine/odoo-docker-compose#1]
Hello, I am getting error installing odoo. could please anyone help?

"Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

I have seen the similar issue From  [stackoverflow](https://stackoverflow.com/questions/47813089/docker-nginx-letsencrypt-odoo-error)
Please help?

Logs:
-------
a.fukwe.com 197.234.242.161 - - [06/May/2018:14:34:55 +0000] "GET /favicon.ico HTTP/1.1" 500 291 "https://a.fukwe.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
odoo_1                               | 2018-05-06 14:34:55,690 19 ERROR ? werkzeug: Error on request:
odoo_1                               | Traceback (most recent call last):
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
odoo_1                               |     execute(self.server.app)
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
odoo_1                               |     application_iter = app(environ, start_response)
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 186, in application
odoo_1                               |     return application_unproxied(environ, start_response)
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 172, in application_unproxied
odoo_1                               |     result = handler(environ, start_response)
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1308, in __call__
odoo_1                               |     return self.dispatch(environ, start_response)
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1282, in __call__
odoo_1                               |     return self.app(environ, start_wrapped)
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
odoo_1                               |     return self.app(environ, start_response)
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1445, in dispatch
odoo_1                               |     explicit_session = self.setup_session(httprequest)
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1342, in setup_session
odoo_1                               |     session_gc(self.session_store)
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/odoo/tools/func.py", line 23, in __get__
odoo_1                               |     value = self.fget(obj)
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1293, in session_store
odoo_1                               |     path = odoo.tools.config.session_dir
odoo_1                               |   File "/usr/lib/python2.7/dist-packages/odoo/tools/config.py", line 600, in session_dir
odoo_1                               |     os.makedirs(d, 0700)
odoo_1                               |   File "/usr/lib/python2.7/os.py", line 150, in makedirs
odoo_1                               |     makedirs(head, mode)
odoo_1                               |   File "/usr/lib/python2.7/os.py", line 150, in makedirs
odoo_1                               |     makedirs(head, mode)
odoo_1                               |   File "/usr/lib/python2.7/os.py", line 150, in makedirs
odoo_1                               |     makedirs(head, mode)
odoo_1                               |   File "/usr/lib/python2.7/os.py", line 157, in makedirs
odoo_1                               |     mkdir(name, mode)
odoo_1                               | OSError: [Errno 13] Permission denied: '/var/lib/odoo/.local'
letsencrypt-nginx-proxy-companion    | 2018/05/06 14:35:03 Debounce minTimer fired
letsencrypt-nginx-proxy-companion    | 2018/05/06 14:35:03 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'

**Comment by lem8r** [comment]
Regarding `db` service there should be no issues as long as database service was not renamed.
Odoo has default name for db server set to `db` https://github.com/odoo/docker/blob/master/11.0/entrypoint.sh#L7

Which corresponds to postgre service name in docker-compose file https://github.com/ERP-Ukraine/odoo-docker-compose/blob/master/docker-compose.yml#L59

In you logs there is notice about Permission denied:
```
odoo_1 | OSError: [Errno 13] Permission denied: '/var/lib/odoo/.local'
```
Try to change owner of `./odoo-data` folder or whatever is used for volume.
`chmod -R 777 ./odoo-data` should solve it but it is not best way to handle it.
